// Package tmux boots and addresses the rook-owned tmux server.
//
// rook never reads the user's ~/.tmux.conf and never joins their tmux
// server: every rook session lives on a dedicated socket (-L rook) under
// a config file rook generates (-f). Rook settings are the source of
// truth; the generated file is the boot snapshot of those settings, and
// live changes to a running server go through `tmux set-option` on the
// same socket.
package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SocketName is the tmux -L socket every rook session lives on.
const SocketName = "rook"

// Theme is rook's visual layer over tmux. Colours are tmux colour names,
// and the defaults are ANSI names on purpose: the glass (ghostty) owns
// the palette, rook only decides structure and emphasis, so the bar
// matches whatever terminal theme the user runs.
type Theme struct {
	Accent string // the one loud colour: active window, session marker, borders
	Dim    string // everything that should recede: inactive windows, chrome
}

// Settings is the tmux-facing slice of rook's configuration. Each field
// proxies to one tmux option; nothing else from tmux's option space is
// exposed until it earns a field here.
type Settings struct {
	EscapeTimeMS     int  // escape-time: ESC-key ambiguity delay
	HistoryLimit     int  // history-limit: scrollback lines per pane
	Mouse            bool // mouse: click to select panes, wheel to scroll
	FocusEvents      bool // focus-events: programs learn when their pane focuses
	SetClipboard     bool // set-clipboard: OSC 52 writes reach the system clipboard
	AllowPassthrough bool // allow-passthrough: tenants may emit raw escapes (images etc.)
	ExtendedKeys     bool // extended-keys: modern key encodings survive the hop from ghostty

	Theme Theme
}

// Defaults are rook's opinions. There is deliberately no way to load a
// user tmux.conf; when users need knobs, they get rook settings.
func Defaults() Settings {
	return Settings{
		EscapeTimeMS:     10,
		HistoryLimit:     100000,
		Mouse:            true,
		FocusEvents:      true,
		SetClipboard:     true,
		AllowPassthrough: true,
		ExtendedKeys:     true,
		Theme: Theme{
			Accent: "yellow",
			Dim:    "brightblack",
		},
	}
}

func onOff(b bool) string {
	if b {
		return "on"
	}
	return "off"
}

// Render emits the tmux.conf for these settings, deterministically.
// confPath is the file this config will live at; the reload binding
// points back at it.
func (s Settings) Render(confPath string) string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# Generated by rook — do not edit; edits are overwritten on every boot.")
	p("# The source of truth is rook's settings.")

	p("")
	p("## terminal")
	p("set -g default-terminal %q", "tmux-256color")
	p("set -sa terminal-features %q", ",xterm-ghostty:RGB")
	p("set -sg escape-time %d", s.EscapeTimeMS)
	p("set -g extended-keys %s", onOff(s.ExtendedKeys))
	p("set -g allow-passthrough %s", onOff(s.AllowPassthrough))
	p("set -g set-clipboard %s", onOff(s.SetClipboard))
	p("set -g focus-events %s", onOff(s.FocusEvents))

	p("")
	p("## behavior")
	p("set -g history-limit %d", s.HistoryLimit)
	p("set -g mouse %s", onOff(s.Mouse))
	p("set -g base-index 1")
	p("setw -g pane-base-index 1")
	p("set -g renumber-windows on")
	p("setw -g aggressive-resize on")
	// The glass shows where you are even when the bar is covered.
	p("set -g set-titles on")
	p("set -g set-titles-string %q", "#S · #W — rook")
	// Closing a session's last window hops to another session instead of
	// dumping the client back to a bare shell: rook is a place, not a run.
	p("set -g detach-on-destroy off")
	p("set -g display-time 2000")
	p("setw -g mode-keys vi")

	p("")
	p("## keys")
	// Splits and new windows continue where you are, not where the
	// session started.
	p(`bind '|' split-window -h -c "#{pane_current_path}"`)
	p(`bind - split-window -v -c "#{pane_current_path}"`)
	p(`bind c new-window -c "#{pane_current_path}"`)
	p("bind -r h select-pane -L")
	p("bind -r j select-pane -D")
	p("bind -r k select-pane -U")
	p("bind -r l select-pane -R")
	p("bind -T copy-mode-vi v send -X begin-selection")
	p("bind -T copy-mode-vi y send -X copy-selection-and-cancel")
	p("bind r source-file %q \\; display %q", confPath, "rook settings applied")

	t := s.Theme
	p("")
	p("## theme — structure from rook, palette from the glass")
	p("set -g status-position bottom")
	p("set -g status-interval 5")
	p("set -g status-justify left")
	p("set -g status-style %q", "bg=default,fg="+t.Dim)
	// ♜ names the server; reverse-video while the prefix is held so the
	// modal state is always visible.
	p("set -g status-left %q", "#[fg="+t.Accent+",bold]#{?client_prefix,#[reverse],} ♜ #S #[default]  ")
	p("set -g status-left-length 40")
	// Empty on purpose: the right side is reserved for the attention
	// layer; until it exists, silence beats a hostname and a clock.
	p("set -g status-right %q", "")
	p("set -g window-status-format %q", "#[fg="+t.Dim+"] #I·#W ")
	p("set -g window-status-current-format %q", "#[fg="+t.Accent+",bold] #I·#W#{?window_zoomed_flag, ⛶,} ")
	p("set -g window-status-separator %q", "")
	p("set -g pane-border-style %q", "fg="+t.Dim)
	p("set -g pane-active-border-style %q", "fg="+t.Accent)
	p("set -g message-style %q", "bg=default,fg="+t.Accent)
	p("set -g mode-style %q", "fg=black,bg="+t.Accent)
	p("set -g clock-mode-colour %s", t.Accent)

	return b.String()
}

// WriteConf renders settings into rook's state directory and returns the
// path, writing atomically so a booting server never reads a torn file.
func WriteConf(s Settings) (string, error) {
	dir := os.Getenv("XDG_STATE_HOME")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		dir = filepath.Join(home, ".local", "state")
	}
	dir = filepath.Join(dir, "rook")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "tmux.conf")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(s.Render(path)), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", err
	}
	return path, nil
}

// Argv builds a tmux invocation addressed at the rook server.
func Argv(confPath string, cmd ...string) ([]string, error) {
	bin, err := exec.LookPath("tmux")
	if err != nil {
		return nil, fmt.Errorf("tmux not found on PATH: rook runs on tmux (`brew install tmux`)")
	}
	argv := []string{bin, "-L", SocketName, "-f", confPath}
	return append(argv, cmd...), nil
}

// SessionName derives a tmux-safe session name from a directory.
// tmux forbids '.' and ':' in session names.
func SessionName(dir string) string {
	name := filepath.Base(dir)
	if name == "" || name == "/" || name == "." {
		return "rook"
	}
	return strings.NewReplacer(".", "_", ":", "_").Replace(name)
}
