// Package tmux boots and addresses the rook-owned tmux server.
//
// rook never reads the user's ~/.tmux.conf and never joins their tmux
// server: every rook session lives on a dedicated socket (-L rook) under
// a config file rook generates (-f). Rook settings are the source of
// truth; the generated file is the boot snapshot of those settings, and
// live changes to a running server go through `tmux set-option` on the
// same socket.
package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SocketName is the tmux -L socket rook talks to: $ROOK_SOCKET when
// set — that's how sandboxes (scripts/sandbox.sh) get a server of
// their own — "rook" otherwise.
func SocketName() string {
	if s := os.Getenv("ROOK_SOCKET"); s != "" {
		return s
	}
	return "rook"
}

// Theme is rook's visual layer over tmux. Colours are tmux colour names,
// and the defaults are ANSI names on purpose: the glass (ghostty) owns
// the palette, rook only decides structure and emphasis, so the bar
// matches whatever terminal theme the user runs.
type Theme struct {
	Accent string // the one loud colour: active window, session marker, borders
	Dim    string // everything that should recede: inactive windows, chrome
}

// Settings is the tmux-facing slice of rook's configuration. Each field
// proxies to one tmux option; nothing else from tmux's option space is
// exposed until it earns a field here.
type Settings struct {
	Prefix           string // prefix: the leader key, in tmux key syntax ("C-b", "`")
	EscapeTimeMS     int    // escape-time: ESC-key ambiguity delay
	HistoryLimit     int  // history-limit: scrollback lines per pane
	Mouse            bool // mouse: click to select panes, wheel to scroll
	FocusEvents      bool // focus-events: programs learn when their pane focuses
	SetClipboard     bool // set-clipboard: OSC 52 writes reach the system clipboard
	AllowPassthrough bool // allow-passthrough: tenants may emit raw escapes (images etc.)
	ExtendedKeys     bool // extended-keys: modern key encodings survive the hop from ghostty

	Theme Theme

	// PluginScripts are absolute paths of plugin *.tmux scripts to
	// run-shell at boot, as resolved by EnsurePlugins.
	PluginScripts []string

	// Companion, when its Command is set, binds a prefix key that
	// summons a popup running Command with rook context in its env.
	Companion Companion
}

// Companion mirrors config.Companion with defaults resolved.
type Companion struct {
	Command string
	Name    string
	Key     string
}

// Defaults are rook's opinions. There is deliberately no way to load a
// user tmux.conf; when users need knobs, they get rook settings.
func Defaults() Settings {
	return Settings{
		Prefix:           "C-b",
		EscapeTimeMS:     10,
		HistoryLimit:     100000,
		Mouse:            true,
		FocusEvents:      true,
		SetClipboard:     true,
		AllowPassthrough: true,
		ExtendedKeys:     true,
		Theme: Theme{
			Accent: "yellow",
			Dim:    "brightblack",
		},
	}
}

func onOff(b bool) string {
	if b {
		return "on"
	}
	return "off"
}

// Render emits the tmux.conf for these settings, deterministically.
// confPath is the file this config will live at; the reload binding
// points back at it.
func (s Settings) Render(confPath string) string {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# Generated by rook — do not edit; edits are overwritten on every boot.")
	p("# The source of truth is rook's settings.")

	p("")
	p("## terminal")
	p("set -g default-terminal %q", "tmux-256color")
	p("set -sa terminal-features %q", ",xterm-ghostty:RGB")
	p("set -sg escape-time %d", s.EscapeTimeMS)
	p("set -g extended-keys %s", onOff(s.ExtendedKeys))
	p("set -g allow-passthrough %s", onOff(s.AllowPassthrough))
	p("set -g set-clipboard %s", onOff(s.SetClipboard))
	p("set -g focus-events %s", onOff(s.FocusEvents))

	p("")
	p("## behavior")
	p("set -g history-limit %d", s.HistoryLimit)
	p("set -g mouse %s", onOff(s.Mouse))
	p("set -g base-index 1")
	p("setw -g pane-base-index 1")
	p("set -g renumber-windows on")
	p("setw -g aggressive-resize on")
	// The glass shows where you are even when the bar is covered.
	p("set -g set-titles on")
	p("set -g set-titles-string %q", "#S · #W — rook")
	// Claude Code's native install names its binary by version, so the
	// honest pane_current_command is "2.1.236" — a window name with no
	// information. Map version-string commands to their real identity.
	p("set -g automatic-rename-format %q",
		"#{?#{m/r:^[0-9.]+$,#{pane_current_command}},claude,#{pane_current_command}}")
	// Closing a session's last window hops to another session instead of
	// dumping the client back to a bare shell: rook is a place, not a run.
	p("set -g detach-on-destroy off")
	p("set -g display-time 2000")
	p("setw -g mode-keys vi")

	p("")
	p("## keys")
	if s.Prefix != "C-b" {
		p("set -g prefix %q", s.Prefix)
		p("unbind C-b")
	}
	// Double-tapping the prefix types it literally — with a backtick
	// prefix this is what keeps markdown fences typeable.
	p("bind %q send-prefix", s.Prefix)
	// Splits and new windows continue where you are, not where the
	// session started.
	p(`bind '|' split-window -h -c "#{pane_current_path}"`)
	p(`bind - split-window -v -c "#{pane_current_path}"`)
	// v is vim's vsplit: side-by-side. That is tmux's -h — the two
	// tools name the axis oppositely, and vim fingers win here.
	p(`bind v split-window -h -c "#{pane_current_path}"`)
	p(`bind c new-window -c "#{pane_current_path}"`)
	p("bind -r h select-pane -L")
	p("bind -r j select-pane -D")
	p("bind -r k select-pane -U")
	p("bind -r l select-pane -R")
	p("bind -T copy-mode-vi v send -X begin-selection")
	p("bind -T copy-mode-vi y send -X copy-selection-and-cancel")
	p("bind r source-file %q \\; display %q", confPath, "rook settings applied")
	// Navigator-style plugins claim root-table C-l; prefix C-l always
	// reaches the shell's clear-screen. Harmless when nothing claims it.
	p("bind C-l send-keys C-l")
	// prefix-s replaces choose-tree with the sesh picker: sessions,
	// zoxide-ranked directories and sesh configs, one fzf popup.
	p("bind s display-popup -E -w 70%% -h 60%% %q", pickerPath(confPath))

	t := s.Theme
	p("")
	p("## theme — structure from rook, palette from the glass")
	// The bottom of a terminal is contested: prompts, Claude Code's
	// footer, fzf, vim statuslines. The top is uncontested, so the bar
	// lives there and never stacks against a tenant's own chrome.
	p("set -g status-position top")
	p("set -g status-interval 5")
	p("set -g status-justify left")
	p("set -g status-style %q", "bg=default,fg="+t.Dim)
	// ♜ rook is the brand chip, not the session: reverse-video while
	// the prefix is held so the modal state is always visible.
	p("set -g status-left %q", "#[fg="+t.Accent+",bold]#{?client_prefix,#[reverse],} ♜ rook #[default] ")
	p("set -g status-left-length 20")
	// The right side is the attention layer's: a #() segment polls the
	// feed every status-interval, then the session name, dim. The
	// generating binary's path is baked in, same as the picker.
	rookBin, err := os.Executable()
	if err != nil {
		rookBin = "rook"
	}
	p("set -g status-right %q", "#("+rookBin+" attention --bar)#[fg="+t.Dim+"]#S ")
	p("set -g status-right-length 60")
	// Tabs: generous padding, and the active window is a raised block —
	// dim ground, accent label — instead of bare colored text.
	p("set -g window-status-format %q", "#[fg="+t.Dim+"]  #I·#W  ")
	p("set -g window-status-current-format %q", "#[fg="+t.Accent+",bg="+t.Dim+",bold]  #I·#W#{?window_zoomed_flag, ⛶,}  ")
	p("set -g window-status-separator %q", "")
	p("set -g pane-border-style %q", "fg="+t.Dim)
	p("set -g pane-active-border-style %q", "fg="+t.Accent)
	p("set -g message-style %q", "bg=default,fg="+t.Accent)
	p("set -g mode-style %q", "fg=black,bg="+t.Accent)
	p("set -g clock-mode-colour %s", t.Accent)
	p("set -g popup-border-lines rounded")
	p("set -g popup-border-style %q", "fg="+t.Dim)

	if s.Companion.Command != "" {
		p("")
		p("## companion — %s: one keystroke away, everywhere", s.Companion.Name)
		// display-popup does NOT format-expand its shell-command, so the
		// binding goes through run-shell -b, which does: the companion
		// opens knowing where it was summoned from, on the client that
		// summoned it.
		inner := fmt.Sprintf(`tmux display-popup -c '#{client_tty}' -E -T ' ♜ %s ' -w 75%% -h 70%% "ROOK_SESSION='#{session_name}' ROOK_DIR='#{pane_current_path}' ROOK_PANE='#{pane_id}' %s"`,
			s.Companion.Name, companionPath(confPath))
		p("bind %s run-shell -b %q", s.Companion.Key, inner)
	}

	if len(s.PluginScripts) > 0 {
		p("")
		p("## plugins — cloned and wired by rook, no TPM")
		for _, script := range s.PluginScripts {
			p("run-shell %q", script)
		}
	}

	return b.String()
}

// pickerPath is where the generated session-picker script lives,
// beside the conf that binds it.
func pickerPath(confPath string) string {
	return filepath.Join(filepath.Dir(confPath), "sesh-picker.sh")
}

// pickerScript is the prefix-s session switcher: rook lists (sessions
// plus zoxide-ranked dirs), fzf chooses with a rook-drawn detail pane,
// rook connects. A script rather than a conf one-liner so the quoting
// has a home and Esc quietly closes the popup. The rook binary's path
// is baked in so a sandbox drives its own build, not whatever is on
// PATH.
func pickerScriptFor(rookBin string) string {
	return fmt.Sprintf(`#!/bin/sh
# Generated by rook — do not edit; edits are overwritten on every boot.
ROOK=%q
selected="$("$ROOK" ls | fzf --ansi --no-sort --reverse \
  --prompt '%s ' \
  --header 'C-a all - C-t sessions - C-x dirs - C-d kill' \
  --preview "$ROOK preview {}" \
  --preview-window 'right,55%%,border-left' \
  --bind "ctrl-a:change-prompt(%s )+reload($ROOK ls)" \
  --bind "ctrl-t:change-prompt(%s session )+reload($ROOK ls -t)" \
  --bind "ctrl-x:change-prompt(%s dir )+reload($ROOK ls -z)" \
  --bind "ctrl-d:execute(tmux kill-session -t {2..})+reload($ROOK ls -t)")" || exit 0
[ -n "$selected" ] && exec "$ROOK" connect "$selected"
`, rookBin, "♜", "♜", "♜", "♜")
}

// ConfPath is where the generated tmux.conf lives, whether or not it
// exists yet.
func ConfPath() (string, error) {
	dir := os.Getenv("XDG_STATE_HOME")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		dir = filepath.Join(home, ".local", "state")
	}
	return filepath.Join(dir, "rook", "tmux.conf"), nil
}

// companionPath is where the generated companion launcher lives,
// beside the conf that binds it.
func companionPath(confPath string) string {
	return filepath.Join(filepath.Dir(confPath), "companion.sh")
}

// companionScript wraps the configured command so quoting has a home
// and the slot can grow (persistent companion sessions, richer
// context) without the conf binding changing shape.
func companionScript(command string) string {
	return "#!/bin/sh\n# Generated by rook — do not edit; edits are overwritten on every boot.\nexec " + command + "\n"
}

// WriteConf renders settings into rook's state directory and returns the
// path, writing atomically so a booting server never reads a torn file.
func WriteConf(s Settings) (string, error) {
	path, err := ConfPath()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	rookBin, err := os.Executable()
	if err != nil {
		return "", err
	}
	if err := writeAtomic(pickerPath(path), pickerScriptFor(rookBin), 0o755); err != nil {
		return "", err
	}
	if s.Companion.Command != "" {
		if err := writeAtomic(companionPath(path), companionScript(s.Companion.Command), 0o755); err != nil {
			return "", err
		}
	}
	if err := writeAtomic(path, s.Render(path), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func writeAtomic(path, content string, mode os.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), mode); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// Argv builds a tmux invocation addressed at the rook server.
func Argv(confPath string, cmd ...string) ([]string, error) {
	bin, err := exec.LookPath("tmux")
	if err != nil {
		return nil, fmt.Errorf("tmux not found on PATH: rook runs on tmux (`brew install tmux`)")
	}
	argv := []string{bin, "-L", SocketName(), "-f", confPath}
	return append(argv, cmd...), nil
}

// SessionName derives a tmux-safe session name from a directory.
// tmux forbids '.' and ':' in session names.
func SessionName(dir string) string {
	name := filepath.Base(dir)
	if name == "" || name == "/" || name == "." {
		return "rook"
	}
	return strings.NewReplacer(".", "_", ":", "_").Replace(name)
}
