// Package tmux boots and addresses the rook-owned tmux server.
//
// rook never reads the user's ~/.tmux.conf and never joins their tmux
// server: every rook session lives on a dedicated socket (-L rook) under
// a config file rook generates (-f). Rook settings are the source of
// truth; the generated file is the boot snapshot of those settings, and
// live changes to a running server go through `tmux set-option` on the
// same socket.
package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// SocketName is the tmux -L socket every rook session lives on.
const SocketName = "rook"

// Settings is the tmux-facing slice of rook's configuration. Each field
// proxies to one tmux option; nothing else from tmux's option space is
// exposed until it earns a field here.
type Settings struct {
	EscapeTimeMS     int  // escape-time: ESC-key ambiguity delay
	HistoryLimit     int  // history-limit: scrollback lines per pane
	Mouse            bool // mouse: click to select panes, wheel to scroll
	FocusEvents      bool // focus-events: programs learn when their pane focuses
	SetClipboard     bool // set-clipboard: OSC 52 writes reach the system clipboard
	AllowPassthrough bool // allow-passthrough: tenants may emit raw escapes (images etc.)
	ExtendedKeys     bool // extended-keys: modern key encodings survive the hop from ghostty
}

// Defaults are rook's opinions. There is deliberately no way to load a
// user tmux.conf; when users need knobs, they get rook settings.
func Defaults() Settings {
	return Settings{
		EscapeTimeMS:     10,
		HistoryLimit:     100000,
		Mouse:            true,
		FocusEvents:      true,
		SetClipboard:     true,
		AllowPassthrough: true,
		ExtendedKeys:     true,
	}
}

func onOff(b bool) string {
	if b {
		return "on"
	}
	return "off"
}

// Render emits the tmux.conf for these settings, deterministically.
func (s Settings) Render() string {
	var b strings.Builder
	b.WriteString("# Generated by rook — do not edit; edits are overwritten on every boot.\n")
	b.WriteString("# The source of truth is rook's settings.\n\n")
	fmt.Fprintf(&b, "set -g default-terminal %q\n", "tmux-256color")
	fmt.Fprintf(&b, "set -sg escape-time %d\n", s.EscapeTimeMS)
	fmt.Fprintf(&b, "set -g history-limit %d\n", s.HistoryLimit)
	fmt.Fprintf(&b, "set -g mouse %s\n", onOff(s.Mouse))
	fmt.Fprintf(&b, "set -g focus-events %s\n", onOff(s.FocusEvents))
	fmt.Fprintf(&b, "set -g set-clipboard %s\n", onOff(s.SetClipboard))
	fmt.Fprintf(&b, "set -g allow-passthrough %s\n", onOff(s.AllowPassthrough))
	fmt.Fprintf(&b, "set -g extended-keys %s\n", onOff(s.ExtendedKeys))
	return b.String()
}

// WriteConf renders settings into rook's state directory and returns the
// path, writing atomically so a booting server never reads a torn file.
func WriteConf(s Settings) (string, error) {
	dir := os.Getenv("XDG_STATE_HOME")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		dir = filepath.Join(home, ".local", "state")
	}
	dir = filepath.Join(dir, "rook")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "tmux.conf")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(s.Render()), 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", err
	}
	return path, nil
}

// Argv builds a tmux invocation addressed at the rook server.
func Argv(confPath string, cmd ...string) ([]string, error) {
	bin, err := exec.LookPath("tmux")
	if err != nil {
		return nil, fmt.Errorf("tmux not found on PATH: rook runs on tmux (`brew install tmux`)")
	}
	argv := []string{bin, "-L", SocketName, "-f", confPath}
	return append(argv, cmd...), nil
}

// SessionName derives a tmux-safe session name from a directory.
// tmux forbids '.' and ':' in session names.
func SessionName(dir string) string {
	name := filepath.Base(dir)
	name = strings.NewReplacer(".", "_", ":", "_").Replace(name)
	if name == "" || name == "/" {
		return "rook"
	}
	return name
}
