// Code generated by scripts/gen-cmds.sh from app/src/registry.zig. DO NOT EDIT.
//
// One constant per canonical registry command id. Aliases are not
// here on purpose: the SDK speaks canon, the app keeps accepting
// the old spellings from hand-written graphs.
package rook

const (
	CmdAppFullscreen   Cmd = "app.fullscreen"
	CmdConfigApply     Cmd = "config.apply"
	CmdConfigEdit      Cmd = "config.edit"
	CmdConfigPreview   Cmd = "config.preview"
	CmdConfigSetup     Cmd = "config.setup"
	CmdPaletteCommands Cmd = "palette.commands"
	CmdPaletteFiles    Cmd = "palette.files"
	CmdPaneClose       Cmd = "pane.close"
	CmdPaneFocusDown   Cmd = "pane.focus-down"
	CmdPaneFocusLeft   Cmd = "pane.focus-left"
	CmdPaneFocusRight  Cmd = "pane.focus-right"
	CmdPaneFocusUp     Cmd = "pane.focus-up"
	CmdPaneScrollback  Cmd = "pane.scrollback"
	CmdPaneSplitDown   Cmd = "pane.split-down"
	CmdPaneSplitRight  Cmd = "pane.split-right"
	CmdPaneZoom        Cmd = "pane.zoom"
	CmdPanelClose      Cmd = "panel.close"
	CmdPanelFlip       Cmd = "panel.flip"
	CmdPanelSearch     Cmd = "panel.search"
	CmdPluginOpen      Cmd = "plugin.open"
	CmdPluginPin       Cmd = "plugin.pin"
	CmdTabNew          Cmd = "tab.new"
	CmdTabNext         Cmd = "tab.next"
	CmdTabPrev         Cmd = "tab.prev"
	CmdTreeReveal      Cmd = "tree.reveal"
	CmdTreeToggle      Cmd = "tree.toggle"
	CmdWorkspaceSwitch Cmd = "workspace.switch"
)
