// GENERATED by scripts/vendor-grammars.mjs — do not edit by hand.
// The vendored grammar set: Monaco language id, TextMate scope, and the
// loader for the grammar JSON (vite splits each into its own lazy chunk, so
// opening a Go file never downloads the TypeScript grammar).

export interface GrammarEntry {
    /** the Monaco language id this grammar tokenizes */
    lang: string;
    /** the TextMate scope name, e.g. "source.go" */
    scope: string;
    /** file extensions, for languages Monaco doesn't already register */
    extensions?: string[];
    load: () => Promise<unknown>;
}

export const GRAMMARS: GrammarEntry[] = [
    {
        lang: "go",
        scope: "source.go",
        load: () => import("./grammars/go.json"),
    },
    {
        lang: "typescript",
        scope: "source.ts",
        load: () => import("./grammars/typescript.json"),
    },
    {
        lang: "javascript",
        scope: "source.js",
        load: () => import("./grammars/javascript.json"),
    },
    {
        lang: "json",
        scope: "source.json",
        load: () => import("./grammars/json.json"),
    },
    {
        lang: "html",
        scope: "text.html.basic",
        load: () => import("./grammars/html.json"),
    },
    {
        lang: "css",
        scope: "source.css",
        load: () => import("./grammars/css.json"),
    },
    {
        lang: "markdown",
        scope: "text.html.markdown",
        load: () => import("./grammars/markdown.json"),
    },
    {
        lang: "shell",
        scope: "source.shell",
        load: () => import("./grammars/shellscript.json"),
    },
    {
        lang: "yaml",
        scope: "source.yaml",
        load: () => import("./grammars/yaml.json"),
    },
    {
        lang: "rust",
        scope: "source.rust",
        load: () => import("./grammars/rust.json"),
    },
    {
        lang: "python",
        scope: "source.python",
        load: () => import("./grammars/python.json"),
    },
    {
        lang: "svelte",
        scope: "source.svelte",
        load: () => import("./grammars/svelte.json"),
    },
];
