// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataEvent carries one chunk of PTY output. Data is base64 because chunks
 * can split UTF-8 sequences mid-rune and JSON cannot carry invalid UTF-8;
 * xterm.js decodes the raw bytes with its own stream-safe decoder.
 */
export interface DataEvent {
    "id": string;
    "data": string;
}

export interface ExitEvent {
    "id": string;
}
