// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Endpoint returns the WebSocket base URL; the frontend appends /session/{id}.
 */
export function Endpoint(): $CancellablePromise<string> {
    return $Call.ByID(2519454032);
}

export function Kill(id: string): $CancellablePromise<void> {
    return $Call.ByID(3412555821, id);
}

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2932850485, id, cols, rows);
}

export function Spawn(cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(450212180, cols, rows);
}
