// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "fontFamily": string;
    "fontSize": number;
    "backgroundOpacity": number;
    "windowPaddingX": number;
    "windowPaddingY": number;

    /**
     * DashboardTab is the strip number the dashboard occupies; shell
     * windows number from the next one up (` <n> follows along).
     */
    "dashboardTab": number;

    /**
     * Agent settings (docs/agent.md): read by rook-agent, never by the
     * host — the host supervises the process, the process reads its own
     * policy. Off by default; the whole feature is opt-in.
     */
    "agent": boolean;
    "agentModel": string;
    "agentDailyCapUsd": number;

    /**
     * Jira issue queue (host-read): jira-url + jira-email are global; a
     * workspace opts in with `jira-project-<workspace> = KEY`. The API
     * token lives in the keychain (rookctl set-jira-token), file fallback
     * ~/.config/rook/jira-token. jira-jql replaces the default query.
     */
    "jiraUrl": string;
    "jiraEmail": string;
    "jiraJql": string;
    "jiraProjects": { [_ in string]?: string } | null;

    /**
     * BranchPrefixes maps a workspace to its worktree-branch prefix,
     * `branch-prefix-<workspace> = seth/`. The value is used verbatim
     * (bring your own trailing separator); unset means rook/.
     */
    "branchPrefixes": { [_ in string]?: string } | null;

    /**
     * Coder is the CLI the host types into spawned task windows (spawn
     * drafts, the conflict-resolve chip, workflow stages). claude unless
     * overridden.
     */
    "coder": string;

    /**
     * Workflow is the staged review pipeline run after a worktree's coding
     * agent opens its PR: slash commands, comma-separated (`workflow =
     * /security-review, /review`), each spawned sequentially in its own
     * window. Empty = feature off. Workflows carries per-workspace
     * overrides (`workflow-<ws> = ...`); an explicitly empty value there
     * is a non-nil empty list — that workspace opts out of the global
     * pipeline.
     */
    "workflow": string[] | null;
    "workflows": { [_ in string]?: string[] | null } | null;

    /**
     * Leader is the tmux-style prefix that arms the bare-key bindings: a
     * single key (`leader = \`, the backtick default) or a modifier chord
     * (`leader = ctrl+b`, the tmux default). Pressing it twice passes the
     * leader through to the terminal. The frontend owns parsing and falls
     * back to the backtick on anything it can't read.
     */
    "leader": string;

    /**
     * Keybinds maps a trigger to a registry command id, ghostty-style:
     * `keybind = <trigger>=<command>`, repeated per binding. A bare key
     * ("h") acts after the leader prefix; a modifier chord
     * ("cmd+shift+]") acts directly. An empty command ("keybind = h=")
     * unbinds the trigger's default. The frontend owns validation and
     * fails open: unknown commands, unparseable chords, and reserved
     * triggers (digits, the literal-backtick escape) are ignored there.
     */
    "keybinds": { [_ in string]?: string } | null;

    /**
     * WorkspaceAllow is a presentation-only visibility filter: when
     * non-empty, only the named workspaces (and any worktree carved from
     * one of them) appear in the host's workspace list — the dashboard,
     * mission control, and /overview. Empty/unset means every workspace
     * shows. `workspace-allow = rook, dora`. Not access control:
     * registration and per-workspace endpoints are unaffected.
     */
    "workspaceAllow": string[] | null;
}

/**
 * Patch is the subset of config the Settings UI edits. A nil pointer / nil map
 * means "leave untouched"; a non-nil value (even empty) is applied. Everything
 * not named here — comments, blank lines, out-of-scope keys — is preserved.
 */
export interface Patch {
    "jiraUrl"?: string | null;
    "jiraEmail"?: string | null;
    "jiraJql"?: string | null;
    "leader"?: string | null;
    "fontFamily"?: string | null;
    "fontSize"?: number | null;

    /**
     * Projects: the full desired jira-project-<ws> map. Rows not present are
     * deleted; rows present are upserted.
     */
    "projects"?: { [_ in string]?: string } | null;

    /**
     * Keybinds: the full desired keybind set (trigger -> command; "" command =
     * unbind line). Replaces the entire keybind block.
     */
    "keybinds"?: { [_ in string]?: string } | null;
}
