// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "fontFamily": string;
    "fontSize": number;
    "backgroundOpacity": number;
    "windowPaddingX": number;
    "windowPaddingY": number;

    /**
     * DashboardTab is the strip number the dashboard occupies; shell
     * windows number from the next one up (` <n> follows along).
     */
    "dashboardTab": number;

    /**
     * Agent settings (docs/agent.md): read by rook-agent, never by the
     * host — the host supervises the process, the process reads its own
     * policy. Off by default; the whole feature is opt-in.
     */
    "agent": boolean;
    "agentModel": string;
    "agentDailyCapUsd": number;

    /**
     * Jira issue queue (host-read): jira-url + jira-email are global; a
     * workspace opts in with `jira-project-<workspace> = KEY`. The API
     * token lives in the keychain (rookctl set-jira-token), file fallback
     * ~/.config/rook/jira-token. jira-jql replaces the default query.
     */
    "jiraUrl": string;
    "jiraEmail": string;
    "jiraJql": string;
    "jiraProjects": { [_ in string]?: string } | null;

    /**
     * BranchPrefixes maps a workspace to its worktree-branch prefix,
     * `branch-prefix-<workspace> = seth/`. The value is used verbatim
     * (bring your own trailing separator); unset means rook/.
     */
    "branchPrefixes": { [_ in string]?: string } | null;

    /**
     * Coder is the CLI the host types into spawned task windows (spawn
     * drafts, the conflict-resolve chip, workflow stages). claude unless
     * overridden.
     */
    "coder": string;
}
