// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "fontFamily": string;
    "fontSize": number;
    "backgroundOpacity": number;
    "windowPaddingX": number;
    "windowPaddingY": number;

    /**
     * DashboardTab is the strip number the dashboard occupies; shell
     * windows number from the next one up (` <n> follows along).
     */
    "dashboardTab": number;
}
