// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearJiraToken(): $CancellablePromise<void> {
    return $Call.ByID(3300020977);
}

export function ClearOpenAIKey(): $CancellablePromise<void> {
    return $Call.ByID(2969362405);
}

/**
 * Get re-reads the file on every call, so a page reload picks up edits
 * without restarting the app.
 */
export function Get(): $CancellablePromise<$models.Config> {
    return $Call.ByID(1220524577);
}

/**
 * JiraTokenStatus reports where the token lives: "keychain", "file"
 * (~/.config/rook/jira-token, 0600), or "" for none.
 */
export function JiraTokenStatus(): $CancellablePromise<string> {
    return $Call.ByID(2498627626);
}

/**
 * OpenAIKeyStatus reports where a usable key currently lives: "keychain",
 * "file" (the ~/.config/rook/openai-key fallback), or "" for none.
 */
export function OpenAIKeyStatus(): $CancellablePromise<string> {
    return $Call.ByID(591849110);
}

/**
 * SetConfig applies a Patch surgically to the config file.
 */
export function SetConfig(p: $models.Patch): $CancellablePromise<void> {
    return $Call.ByID(1981843071, p);
}

/**
 * SetJiraToken stores the Jira API token in the login keychain (service rook,
 * account jira). Entering it here — not on a shell — is why special characters
 * like underscores survive.
 */
export function SetJiraToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(872166990, token);
}

/**
 * SetOpenAIKey stores the drafter's API key in the login keychain.
 */
export function SetOpenAIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(3580416418, key);
}
