// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as session$0 from "../../../../incantery/rook/internal/session/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "pty:data": session$0.DataEvent;
            "pty:exit": session$0.ExitEvent;
        }
    }
}
