package vt

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"testing"
)

// The fidelity gate. Whatever xterm.js 6.0.0 renders is, by definition, what
// rook shows today, so its grid is ground truth: this feeds every corpus
// capture through our emulator at the capture geometry and diffs the result
// against a frozen xterm grid, cell for cell. A char or width divergence
// corrupts the display; a fg/bg/attr divergence is usually cosmetic. Golden
// grids are regenerated by testdata/gen.sh (the vendored xterm.js oracle)
// whenever the corpus grows.

type goldenCell struct {
	C  string `json:"c"`
	W  int    `json:"w"`
	Fg string `json:"fg"`
	Bg string `json:"bg"`
	A  string `json:"a"`
}

type goldenGrid struct {
	Name  string         `json:"name"`
	Cols  int            `json:"cols"`
	Rows  int            `json:"rows"`
	Cells [][]goldenCell `json:"cells"`
}

type meta struct {
	Cols int `json:"cols"`
	Rows int `json:"rows"`
}

// perCorpusFloor is the match rate each capture must clear. The deterministic,
// ASCII-and-SGR captures must be perfect; the adversarial-unicode one carries a
// small, understood allowance for the contested width of ZWJ emoji families.
var perCorpusFloor = map[string]float64{
	"git-graph": 100.0,
	"longlines": 100.0,
	"nvim-edit": 100.0,
	"redraw":    100.0,
	"unicode":   98.5,
}

func TestFidelity(t *testing.T) {
	golden, err := filepath.Glob("testdata/golden/*.json")
	if err != nil || len(golden) == 0 {
		t.Fatalf("no golden grids under testdata/golden (err=%v)", err)
	}
	for _, gpath := range golden {
		name := trimExt(filepath.Base(gpath))
		t.Run(name, func(t *testing.T) {
			g := loadGolden(t, gpath)
			raw, m := loadCapture(t, name)
			if g.Cols != m.Cols || g.Rows != m.Rows {
				t.Fatalf("geometry mismatch: golden %dx%d, meta %dx%d", g.Cols, g.Rows, m.Cols, m.Rows)
			}

			e := New(m.Cols, m.Rows)
			e.Write(raw)

			total := g.Cols * g.Rows
			var diff, corrupting int
			buckets := map[string]int{}
			var samples []string
			for y := range g.Rows {
				for x := range g.Cols {
					want := g.Cells[y][x]
					got := e.CellAt(x, y)
					fields := cellDiff(want, e.Content(got), got)
					if len(fields) == 0 {
						continue
					}
					diff++
					for _, f := range fields {
						buckets[f]++
						if f == "c" || f == "w" {
							corrupting++
						}
					}
					if len(samples) < 12 && (has(fields, "c") || has(fields, "w")) {
						samples = append(samples, fmt.Sprintf(
							"(%2d,%3d) want{c:%q w:%d fg:%s bg:%s a:%q} got{c:%q w:%d fg:%s bg:%s a:%q}",
							y, x, want.C, want.W, want.Fg, want.Bg, want.A,
							e.Content(got), got.Width, got.FG.Token(), got.BG.Token(), got.Attr.Token()))
					}
				}
			}

			match := 100 * float64(total-diff) / float64(total)
			t.Logf("%s (%dx%d, %d cells): %.2f%% identical  [%d diff cells, %d corrupting]",
				name, g.Cols, g.Rows, total, match, diff, corrupting)
			for _, k := range sortedKeys(buckets) {
				t.Logf("    %s differs in %d cells", fieldName(k), buckets[k])
			}
			for _, s := range samples {
				t.Logf("    %s", s)
			}

			if floor, ok := perCorpusFloor[name]; ok && match < floor {
				t.Errorf("%s: %.2f%% identical, want >= %.2f%%", name, match, floor)
			}
		})
	}
}

func cellDiff(want goldenCell, gotContent string, got Cell) []string {
	var fields []string
	if want.C != gotContent {
		fields = append(fields, "c")
	}
	if want.W != int(got.Width) {
		fields = append(fields, "w")
	}
	if want.Fg != got.FG.Token() {
		fields = append(fields, "fg")
	}
	if want.Bg != got.BG.Token() {
		fields = append(fields, "bg")
	}
	if want.A != got.Attr.Token() {
		fields = append(fields, "a")
	}
	return fields
}

func loadGolden(t *testing.T, path string) goldenGrid {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var g goldenGrid
	if err := json.Unmarshal(b, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

// loadCapture reads a corpus capture and its geometry. It takes testing.TB so
// both the fidelity tests and the benchmarks can use it.
func loadCapture(tb testing.TB, name string) ([]byte, meta) {
	tb.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata/corpus", name+".raw"))
	if err != nil {
		tb.Fatal(err)
	}
	mb, err := os.ReadFile(filepath.Join("testdata/corpus", name+".meta.json"))
	if err != nil {
		tb.Fatal(err)
	}
	var m meta
	if err := json.Unmarshal(mb, &m); err != nil {
		tb.Fatal(err)
	}
	return raw, m
}

func trimExt(s string) string { return s[:len(s)-len(filepath.Ext(s))] }

func has(ss []string, s string) bool { return slices.Contains(ss, s) }

func sortedKeys(m map[string]int) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func fieldName(k string) string {
	switch k {
	case "c":
		return "char"
	case "w":
		return "width"
	default:
		return k
	}
}
