#!/bin/sh
# Generate sdk/rook/cmds.go from app/src/registry.zig.
#
# The registry is the ONE command vocabulary — the palette, the ctl
# `run` verb, keybinds and the editor leader all speak it. The SDK's
# typed constants exist so a config that names a dead command fails to
# COMPILE instead of being silently skipped at load; that promise only
# holds if the constants cannot drift, which is why they are generated
# rather than written. CI-able: `make gen-cmds && git diff --exit-code`.
set -eu
cd "$(dirname "$0")/.."

src=app/src/registry.zig
out=sdk/rook/cmds.go

{
    echo "// Code generated by scripts/gen-cmds.sh from app/src/registry.zig. DO NOT EDIT."
    echo "//"
    echo "// One constant per canonical registry command id. Aliases are not"
    echo "// here on purpose: the SDK speaks canon, the app keeps accepting"
    echo "// the old spellings from hand-written graphs."
    echo "package rook"
    echo ""
    echo "const ("
    grep -o '\.id = "[a-z0-9.-]*"' "$src" | sed 's/\.id = "//;s/"$//' | sort -u |
        while read -r id; do
            name=$(printf '%s' "$id" | awk -F'[.-]' '{ for (i = 1; i <= NF; i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2) }')
            printf '\tCmd%s Cmd = "%s"\n' "$name" "$id"
        done
    echo ")"
} > "$out"
gofmt -w "$out"
echo "gen-cmds: $(grep -c '^\tCmd' "$out") commands -> $out"
